Add Fortran module for GEFS data source in CDEPS
NOAA-EMC/CDEPS pull request #13
Opened 2021-03-11 13:10 UTC by binli2337

### Description of changes
The Fortran module for GEFS data source will be added to CDEPS.

### Specific notes
The revised code will include the following changes:
1) The Fortran module for GEFS "datm_datamode_gefs_mod.F90" will be added.
2) The nuopc cap code for data atmosphere model "atm_comp_nuopc.F90" will be updated.
3) CMakeLists.txt file will be updated to compile the updated code using cmake.

Testing performed:
Tests have been done in the mom6_cice6_cdeps application using a revised CMEPS code from ESCOMP/CMEPS (#74f7751, March 5, 2021 version).

2021-03-11 13:11 UTC, binli2337 commented
A related PR for ufs-weather-model will be submitted.

2021-03-11 13:37 UTC, junwang-noaa approved these changes

2021-03-12 17:59 UTC, uturuncoglu requested changes
I could not see CDEPS CFSR specific module file in here. Maybe you forgot to add it to PR.

2021-03-12 17:59 UTC, uturuncoglu commented on datm/datm_datamode_gefs_mod.F90
> +    !----------------------------------------------------------
If there is no need to unit conversion. This part of code can be cleaned.

2021-03-12 18:01 UTC, uturuncoglu commented
> I could not see CDEPS CFSR specific module file in here. Maybe you forgot to add it to PR.

Sorry, that was already merged in previous PR.

2021-03-25 23:34 UTC, merged